[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.9.6"
solady = "0.1.10"
"@openzeppelin-contracts" = "5.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

#configure test fuzz
[fuzz]
runs = 6000
